schemaspy/schemaspy

.gitignore, src/main/java/org/schemaspy/DbAnalyzer.java
fixes missing implied relationships bug. 
new instance for Database object "primary" have to be created for adding it "toduplicatePrimaries" second time.
=> implied relationship fix

pom.xml
replace ${version} with ${project.version}. solves maven warning
=> fix maven warning

src/main/java/org/schemaspy/model/Table.java, src/test/java/org/schemaspy/model/TableFullNameTest.java
Organize imports and adding tests for Table#getFullName
=> Refactoring table class

src/main/java/org/schemaspy/SchemaAnalyzer.java
=> Multiple schema analyse always returned null

src/main/java/org/schemaspy/DbAnalyzer.java, src/main/java/org/schemaspy/model/DatabaseObject.java, src/test/java/org/schemaspy/DbAnalyzerTest.java
improves implied relationship code
code cleanup done. 
adds feature, now its possible to link  
```
transaction.shipping_adress_id like --> adress.adress_id
childTable.%column_id --> parentTable.column_id
```
=> improvements on implied constraint 

src/main/resources/layout/tables/table.html
This enables deep linking to a few more sections
see #50 for further context
=> Add some missing <h3> id's

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/view/DotNode.java
Noticed, that font is not smooth when images was changed to svg.
Increasing font size +1 change this a little bit.
=> Svg images

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/util/Dot.java, src/main/java/org/schemaspy/view/DotNode.java, src/main/java/org/schemaspy/view/HtmlTablePage.java
After discusion with @rafalkasa we think, that png should be default image format and svg to be an option
=> Added imageformat parameter - png is default. svg as an option

src/main/java/org/schemaspy/model/LogicalTable.java, src/main/java/org/schemaspy/model/RemoteTable.java, src/main/java/org/schemaspy/model/Table.java, src/main/java/org/schemaspy/model/TableColumn.java, src/main/java/org/schemaspy/model/View.java, src/test/java/org/schemaspy/DbAnalyzerTest.java
As the SQLException cannot be thrown from the constructors body in
classes Table, LogicalTable, RemoteTable, View and TableColumn, remove
it from the declaration.
=> Fix sonar issue: Remove declaration of thrown exception SQLException

.gitignore, src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/DbDriverLoader.java, src/main/java/org/schemaspy/service/SqlService.java
Fix some extra issue happen after changes in code for impala support
Support for Impala #64
=> Impala support fixes

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/util/HtmlEncoder.java, src/main/java/org/schemaspy/view/DotNode.java, src/main/java/org/schemaspy/view/HtmlColumnsPage.java, src/main/java/org/schemaspy/view/HtmlConstraintsPage.java, src/main/java/org/schemaspy/view/HtmlFormatter.java
I found and removed those unused methods via my IDE (IntelliJ). So it
should be safe. Could not find any bugs or missing things during my
tests afterwards.
If there was unused code that was considered to be used in the future,
please let me know.
=> Remove some dead code, mainly in Html generation classes

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/view/MustacheWriter.java
=> Fix use of template parameter for custom layout director via command line

pom.xml
* Removed redudant dependencies
=> Adde spring-boot-starter-test

pom.xml, src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/DbDriverLoader.java, src/test/java/org/schemaspy/ConfigTest.java, src/test/java/org/schemaspy/DbDriverLoaderTest.java, src/test/java/org/schemaspy/testing/H2MemoryRule.java
loadjars will include .?ar (nar,war,jar), H2MemoryRule for jUnit
* H2Memory rule with script support I believe
* H2 dependency with scope test
* Config constructor change from String[] argv to String... argv
=> Include nar when loading dp sibling libraries

pom.xml, src/test/java/org/schemaspy/service/DatabaseServiceIT.java, src/test/java/org/schemaspy/testing/H2MemoryRule.java, src/test/resources/integrationTesting/h2memory.properties, travis.sh
* Added maven-failsafe-plugin
* Added dbType for h2memory in test resources
* Added getter to H2MemoryRule to access the keepAlive connection for support in test
=> Simple integration test of DatabaseService

docker/snapshot/Dockerfile
Removed characters that shouldnt be there
=> Unknown characters in docker/snapshot/Dockerfile

src/main/resources/org/schemaspy/types/netezza.properties
=> Netezza dbtype

src/main/java/org/schemaspy/service/DatabaseService.java, src/main/java/org/schemaspy/service/SqlService.java, src/main/java/org/schemaspy/service/TableService.java, src/main/java/org/schemaspy/service/ViewService.java
Here are some rationale for this:
http://olivergierke.de/2013/11/why-field-injection-is-evil/
Also organize imports and remove unused imports.
Rename logger by convention.
Addresses issue #91
=> Replace field injection with constructor injection for some Spring Beans

pom.xml, src/test/java/org/schemaspy/testcontainer/MysqlXMLIT.java, src/test/java/org/schemaspy/testcontainer/OracleIT.java, src/test/resources/integrationTesting/dbScripts/mysqlxmlit.sql, src/test/resources/integrationTesting/expecting/mysqlxmlit/deletionOrder.txt, src/test/resources/integrationTesting/expecting/mysqlxmlit/insertionOrder.txt, src/test/resources/integrationTesting/expecting/mysqlxmlit/test.test.xml, src/test/resources/logback-test.xml
* Added xmlunit
* Added expectation
* Test XML, deletionOrder, inserationOrder
=> Test generated XML against a saved, using mysql container.

src/main/java/org/schemaspy/util/Dot.java, src/test/java/org/schemaspy/util/DotTest.java, src/test/resources/dotFakes/2.26.0/bin/dot, src/test/resources/dotFakes/2.26.1/bin/dot, src/test/resources/dotFakes/2.28.0/bin/dot, src/test/resources/dotFakes/2.32.0/bin/dot
=> Skip patch details for Graphviz version.

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/service/SqlService.java, src/main/java/org/schemaspy/util/ConnectionURLBuilder.java, src/main/java/org/schemaspy/util/DbSpecificOption.java, src/main/resources/org/schemaspy/types/db2net.properties, src/main/resources/org/schemaspy/types/derbynet.properties, src/main/resources/org/schemaspy/types/firebird.properties, src/main/resources/org/schemaspy/types/hsqldb.properties, src/main/resources/org/schemaspy/types/impala.properties, src/main/resources/org/schemaspy/types/informix.properties, src/main/resources/org/schemaspy/types/jtds.properties, src/main/resources/org/schemaspy/types/mariadb.properties, src/main/resources/org/schemaspy/types/mssql-jtds-instance.properties, src/main/resources/org/schemaspy/types/mssql-jtds.properties, src/main/resources/org/schemaspy/types/mssql.properties, src/main/resources/org/schemaspy/types/mssql05-jtds-instance.properties, src/main/resources/org/schemaspy/types/mssql05.properties, src/main/resources/org/schemaspy/types/mysql.properties, src/main/resources/org/schemaspy/types/netezza.properties, src/main/resources/org/schemaspy/types/orathin.properties, src/main/resources/org/schemaspy/types/pgsql.properties, src/main/resources/org/schemaspy/types/redshift.properties, src/main/resources/org/schemaspy/types/sybase.properties, src/test/java/org/schemaspy/util/ConnectionURLBuilderTest.java, src/test/resources/dbtypes/hostOptionalPort.properties, src/test/resources/dbtypes/hostOptionalPortCustomSeparator.properties, src/test/resources/dbtypes/onlyHost.properties
Added a constructed value for option `<hostOptionalPort>`
So port is always option.
Separator between host and port can be customized.
Should solve 109.
I.e `-host localhost:3306` and `-host localhost -port 3306` creates the same result.
=> Issue 109 dbtypes

src/main/resources/layout/tables/table.html, src/main/resources/layout/tables/table.js
=> Rename codemirror textarea id

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/view/HtmlRoutinePage.java, src/main/java/org/schemaspy/view/HtmlRoutinesPage.java, src/main/resources/layout/container.html, src/main/resources/layout/routines.html, src/main/resources/layout/routines.js, src/main/resources/layout/routines/routine.html, src/main/resources/layout/routines/routine.js
This is for #145
I added a table page to list all of the routines, and sub-pages for each routine.
I mostly use SqlServer right now, so I also added support for routines to the base SqlServer configuration. I have a note that needs review on how to proceed with this, as it uses `information_schema`, and this is only supported by SQL Server 2012 and newer
=> Convert Routines to Mustache

pom.xml, src/main/java/org/schemaspy/model/Database.java, src/main/java/org/schemaspy/service/TableService.java, src/test/java/org/schemaspy/testcontainer/MysqlSpacesIT.java, src/test/resources/integrationTesting/dbScripts/mysql_spaces.sql
Added db.getQuotedIdentifier() table.getName in initColumns and same to schema/catalog in initColumnAutoUpdate
* Refactored the schema/catalog code in fethNumRows, initColumnAutoUpdate.
* Added a quoteIdentifier method to Database class.
Fixes #134
=> Fixing issue 134 Failed to determine auto increment status

docs/source/configuration.rst, docs/source/index.rst
=> Added documentation regarding DatabaseType

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/DbDriverLoader.java, src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/db/config/PropertiesFinder.java, src/main/java/org/schemaspy/db/config/PropertiesResolver.java, src/main/java/org/schemaspy/db/config/ResolutionInfo.java, src/main/java/org/schemaspy/db/config/ResourceFinder.java, src/main/java/org/schemaspy/db/config/ResourceNotFoundException.java, src/main/java/org/schemaspy/db/exceptions/RuntimeIOException.java, src/main/java/org/schemaspy/service/SqlService.java, src/main/java/org/schemaspy/util/ConnectionURLBuilder.java, src/main/java/org/schemaspy/util/DbSpecificConfig.java, src/test/java/org/schemaspy/ConfigTest.java, src/test/java/org/schemaspy/db/config/PropertiesFinderTest.java, src/test/java/org/schemaspy/db/config/PropertiesResolverTest.java, src/test/resources/dbtypes/B1.properties, src/test/resources/dbtypes/C0.properties, src/test/resources/dbtypes/D0, src/test/resources/org/schemaspy/types/A0.properties, src/test/resources/org/schemaspy/types/A1.properties, src/test/resources/org/schemaspy/types/A2.properties, src/test/resources/org/schemaspy/types/B0.properties, src/test/resources/org/schemaspy/types/E0, src/test/resources/org/schemaspy/types/badInclude.properties
Moving db properties resolution to own class. Making Config more of a value object.
Should help with migration from Config to CommanLineArguments.
=> Moving logic from config

src/main/resources/org/schemaspy/types/mssql08-jtds-instance.properties, src/main/resources/org/schemaspy/types/mssql08-jtds.properties, src/main/resources/org/schemaspy/types/mssql08.properties
=> Switch MSSQL2012 to MSSQL2008

ISSUE_TEMPLATE.md
File was generated by https://www.talater.com/open-source-templates and
extended with things that spontaneously came to my mind.
=> Add issue template for bug reports, feature requests, etc.

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/view/HtmlMainIndexPage.java, src/main/resources/layout/main.html, src/main/resources/layout/routines.html
1. Added to the database summary screen two more information like:
- Anomalies amount
- Routines amount
2. Routines icon was changed
=> Extend database summary

src/main/java/org/schemaspy/output/xml/dom/DOMUtil.java, src/main/java/org/schemaspy/output/xml/dom/XmlProducerUsingDOM.java, src/main/java/org/schemaspy/output/xml/dom/XmlTableFormatter.java, src/test/java/org/schemaspy/output/xml/dom/XmlTableFormatterTest.java
* Added copyright and author if applicable license
* Private constructor
* Removed right side genericType. diamond <>
* Added static variable for strings used often
* refactored to lambda
* refactored to forEach instead of keySet and .get(key)
=> Fixes according to sonar

src/test/java/org/schemaspy/model/InvalidConfigurationExceptionTest.java
This is InvalidConfigurationException class coverage added by the way
=> InvalidConfigurationException class unit tests

src/main/java/org/schemaspy/SchemaSpyConfiguration.java, src/main/java/org/schemaspy/cli/CommandLineArguments.java, src/main/resources/commandlinearguments.properties
* -debug for schemaspy only
* --debug for schemaspy and spring
=> Added commandline argument for enabling debug logging.

src/main/java/org/schemaspy/Revision.java, src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/service/DatabaseService.java
=> Small changes

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/db/config/PropertiesFinder.java, src/main/java/org/schemaspy/db/config/PropertiesResolver.java, src/main/java/org/schemaspy/db/config/ResolutionInfo.java, src/main/java/org/schemaspy/db/config/ResourceFinder.java, src/main/java/org/schemaspy/db/config/ResourceNotFoundException.java, src/main/java/org/schemaspy/db/exceptions/RuntimeIOException.java, src/main/java/org/schemaspy/service/SqlService.java, src/main/java/org/schemaspy/util/ConnectionURLBuilder.java, src/main/java/org/schemaspy/util/DbSpecificConfig.java, src/test/java/org/schemaspy/ConfigTest.java, src/test/java/org/schemaspy/db/config/PropertiesFinderTest.java, src/test/java/org/schemaspy/db/config/PropertiesResolverTest.java
* Un-deprecated getDb from config since it's modified in multiSchema
=> Fixed some sonar issue, added copyright and author

src/main/java/org/schemaspy/util/ResourceFinder.java, src/main/java/org/schemaspy/util/ResourceNotFoundException.java, src/main/java/org/schemaspy/view/MustacheWriter.java, src/test/java/org/schemaspy/util/ResourceFinderTest.java, src/test/resources/resourceFinder.test, src/test/resources/resourceFinderTest/resourceFinder.test
Depends on #234 we want test to be in master before we do the change.
=> Removed spring dependency from MustacheWriter

docs/source/started.rst
Hi @rafalkasa / @npetzall, 
I have made changes to the started.rst file to add information related to -imageformat parameter. 
Please review and let me know if any modifications are needed. 
Thanks in advance.
=> Made changes to resolve https://github.com/schemaspy/schemaspy/issues/241

src/main/java/org/schemaspy/Config.java, src/test/java/org/schemaspy/ConfigTest.java, src/test/resources/configTest/loadpropertiesTest.properties
* Added test for loadProperties
=> Removed dependency on spring from Config

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/WiringConfiguration.java, src/main/java/org/schemaspy/service/DatabaseService.java, src/main/java/org/schemaspy/service/SqlService.java, src/main/java/org/schemaspy/service/TableService.java, src/main/java/org/schemaspy/service/ViewService.java
* Added new wiring configuration
* Left stereotypes in commandline classes
=> Removed stereotype from all classes not tied to application

pom.xml, src/main/java/org/schemaspy/db/config/PropertiesFinder.java
First commit makes failsafe (integration tests use built jar)
This will faile.
After the failure, I'll add the fix that exists in PR #264
=> Use built-jar and fix error

src/main/java/org/schemaspy/Main.java, src/main/java/org/schemaspy/logging/LogLevelConditionalThrowableProxyConverter.java, src/main/resources/META-INF/spring.factories, src/test/java/org/schemaspy/integrationtesting/StackTraceLoggingIT.java
* Changed LogLevelConditionalThrowableProxy... to a ApplicationListener
it's added thru spring.factories
Related to #265 and #249
=> Added test for logging without stacktrace.

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/model/Database.java, src/test/java/org/schemaspy/integrationtesting/H2KeywordIT.java, src/test/java/org/schemaspy/integrationtesting/H2SpacesIT.java, src/test/java/org/schemaspy/integrationtesting/H2ViewIT.java, src/test/java/org/schemaspy/integrationtesting/OracleSpacesIT.java, src/test/java/org/schemaspy/integrationtesting/SchemaMetaIT.java, src/test/java/org/schemaspy/service/DatabaseServiceIT.java, src/test/java/org/schemaspy/testcontainer/InformixIndexIT.java, src/test/java/org/schemaspy/testcontainer/MSSQLServerIT.java, src/test/java/org/schemaspy/testcontainer/MysqlKeyWordTableIT.java, src/test/java/org/schemaspy/testcontainer/MysqlRoutinesIT.java, src/test/java/org/schemaspy/testcontainer/MysqlSpacesIT.java, src/test/java/org/schemaspy/testcontainer/MysqlSpacesNoDotsIT.java, src/test/java/org/schemaspy/testcontainer/OracleIT.java
Progress should be around the model not in the model.
=> Removed unused ProgressListener from Database model

src/test/java/org/schemaspy/util/ResultSetDumper.java
* ResultSetDumper is not a production class
* Added Copyright and author since I've modified the file
=> Moved ResultSetDumper from main to test

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/db/config/PropertiesResolver.java, src/main/java/org/schemaspy/util/ConnectionURLBuilder.java, src/test/java/org/schemaspy/ConfigIT.java, src/test/java/org/schemaspy/testing/ResettingOutputCapture.java
When dbType has missing parameter only that dbType is printed.
Changed reolution logging from info to debug.
Solves #336
=> 336 show only selected database type

pom.xml
Will close #139 for now.
After a release or RC build a second commit will be done updating the version yet again.
After RC build it will be put back to -SNAPSHOT.
After release build it will be set to nextVersion-SNAPSHOT.
=> Version 6.0.0-rc2 to 6.0.0-SNAPSHOT so latest builds will be snapshot

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/view/HtmlFormatter.java
Remove old and unused config options, they don't need to be ported to JCommander.
=> Cleanup config

README.md, docs/source/faq.rst, docs/source/index.rst
=> Osx and graphviz documentation

docs/source/configuration/commandline.rst, docs/source/started.rst
* Added ref link from Commandline connprops to
Started/Advanced/Use connprops.
* Relates to #362
=> Created link from Started to Commandline arguments.

src/main/java/org/schemaspy/DbDriverLoader.java, src/test/java/org/schemaspy/DbDriverLoaderTest.java
=> Fixed logging, not object but content of driverClass array

src/main/java/org/schemaspy/view/DotFormatter.java, src/main/java/org/schemaspy/view/DotNode.java
* minor fixes as suggested by sonarlint
=> Changed ctor File outputDir to String since stored as String

src/main/java/org/schemaspy/model/Schema.java
* squid:ClassVariableVisibilityCheck
* Fixed misspelled author
* Fixed equals method (compare, hashcode uses name only)
=> Made fields private in Schema model

src/main/java/org/schemaspy/model/Catalog.java
* Both compareTo, hashCode uses name
* Minor formatting, annotation above method, empty line between methods
=> Catalog model equals should use name

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/cli/CommandLineArgumentParser.java, src/main/java/org/schemaspy/util/ConnectionURLBuilder.java, src/main/java/org/schemaspy/util/DbSpecificConfig.java, src/test/java/org/schemaspy/util/DbSpecificConfigTest.java
Changed. so that HostOptionalPort isn't printed in the dbhelp output
* Fixes according to sonarlint
Solves #335
=> 335 fix dbhelp output

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/model/CombinedMap.java, src/main/java/org/schemaspy/model/Database.java, src/main/java/org/schemaspy/model/DbmsMeta.java, src/main/java/org/schemaspy/service/DatabaseService.java, src/main/java/org/schemaspy/service/DbmsService.java, src/main/java/org/schemaspy/service/SqlService.java, src/main/java/org/schemaspy/service/TableService.java, src/main/java/org/schemaspy/view/HtmlTablePage.java, src/main/java/org/schemaspy/view/SqlAnalyzer.java, src/test/java/org/schemaspy/integrationtesting/H2KeywordIT.java, src/test/java/org/schemaspy/integrationtesting/H2SpacesIT.java, src/test/java/org/schemaspy/integrationtesting/H2ViewIT.java, src/test/java/org/schemaspy/integrationtesting/OracleSpacesIT.java, src/test/java/org/schemaspy/integrationtesting/SchemaMetaIT.java, src/test/java/org/schemaspy/integrationtesting/mssqlserver/MSSQLServerCheckConstraintIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlKeyWordTableIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlRoutinesIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlSpacesIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlSpacesNoDotsIT.java, src/test/java/org/schemaspy/service/DatabaseServiceIT.java, src/test/java/org/schemaspy/testcontainer/InformixIndexIT.java, src/test/java/org/schemaspy/testcontainer/MSSQLServerIT.java, src/test/java/org/schemaspy/testcontainer/MysqlSchemaLeakageIT.java, src/test/java/org/schemaspy/testcontainer/OracleIT.java
Removed DatabaseMetaData from Database model
* Added new model object DbmsMeta
* Replaced usage in view with DbmsMeta
* Replaced usage in Services (TableService) with getter in SqlService
* Moved QuotedIdentifier handling to SqlService
=> Remove databasemetadata from database

pom.xml, src/main/resources/org/schemaspy/types/mariadb.properties, src/test/java/org/schemaspy/integrationtesting/mariadb/MariaDbRoutinesIT.java
* Fixes #385
* Also fixes an issue with deterministic in mariadb that has been fixed
in mysql
* Added mariadb routines test but is ignored. (don't want to add to
build time)
=> MariaDb databaseType extends mysql

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/cli/SchemaSpyRunner.java, src/main/java/org/schemaspy/db/CatalogResolver.java, src/main/java/org/schemaspy/db/SchemaResolver.java, src/test/java/org/schemaspy/db/CatalogResolverTest.java, src/test/java/org/schemaspy/db/SchemaResolverTest.java
* New EXIT_CODE 4 for InvalidConfigurationException
* Moved Catalog/Schema default/validation to own classes
=> Improved error messages when Catalog or Schema are null

src/main/java/org/schemaspy/view/HtmlRoutinePage.java, src/main/resources/layout/routines/routine.html, src/main/resources/layout/routines/routine.js, src/test/resources/integrationTesting/mysql/dbScripts/htmlit.sql, src/test/resources/integrationTesting/mysql/expecting/mysqlhtml/routines/no_det.html, src/test/resources/integrationTesting/mysql/expecting/mysqlhtml/routines/yes_det.html
Fixed sql for mysql html
Fixed comment in routine page
Fixed definition in routine page
Closes #356 
Closes #357 
Closes #358
=> Routine fixes 356 357 358

.travis.yml, docker.sh
* Travis creates a branch for the tag, so need to be all
else only run on tags or master not both.
* Same change in docker.sh since tag is a branch.
=> Change docker deploy to run on all branches

pom.xml, src/main/resources/org/schemaspy/types/pgsql.properties, src/test/java/org/schemaspy/integrationtesting/PgSqlSuite.java, src/test/java/org/schemaspy/integrationtesting/pgsql/PgSqlCheckConstraintsIT.java, src/test/java/org/schemaspy/integrationtesting/pgsql/PgSqlRoutinesIT.java, src/test/resources/integrationTesting/pgsql/dbScripts/dvdrental.sql
* Added as suite
Works with version 10 and 9.3, only available on docker-hub
=> Added routines and checkconstraint to postgres

pom.xml, src/main/java/org/schemaspy/service/TableService.java, src/test/java/org/schemaspy/integrationtesting/PgSqlSuite.java, src/test/java/org/schemaspy/integrationtesting/pgsql/PgSqlCheckConstraintsIT.java, src/test/java/org/schemaspy/integrationtesting/pgsql/PgSqlRelationshipErrorIT.java, src/test/java/org/schemaspy/testing/SQLScriptsRunner.java, src/test/resources/integrationTesting/pgsql/dbScripts/dvdrental.sql, src/test/resources/integrationTesting/pgsql/dbScripts/relationship_error.sql
* Refactored SQLScriptRunner to be able to customize statment separator
* Fixed exlusion of PgSql*IT.java since suite is used.
* Updated dvdrental to play nice with relationship_error
Fixes #397
=> TableService#addForeignKey use BaseContainer if RemoteTable else Container

src/main/java/org/schemaspy/view/HtmlRoutinesPage.java, src/main/resources/layout/routines.html, src/test/java/org/schemaspy/view/HtmlRoutinesPageTest.java
=> Added comment to routines.html with markdown-processing

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/view/HtmlMultipleSchemasIndexPage.java, src/main/resources/layout/multi.html, src/test/java/org/schemaspy/view/HtmlMultipleSchemasIndexPageTest.java
=> Added description to MultipleSchemasIndexPage

pom.xml, src/main/resources/org/schemaspy/types/pgsql.properties, src/test/java/org/schemaspy/integrationtesting/PgSqlSuite.java, src/test/java/org/schemaspy/integrationtesting/pgsql/PgSqlMaterializedViewsIT.java, src/test/resources/integrationTesting/pgsql/dbScripts/materialized_view.sql
* Added viewType
* Updated query to have union between pg_view and pg_matview
* Added test
=> Added Materialized views with definition.

src/main/java/org/schemaspy/view/MustacheWriter.java, src/main/java/org/schemaspy/view/StyleSheet.java, src/main/java/org/schemaspy/view/StyleSheetConst.java, src/test/java/org/schemaspy/view/MustacheWriterTest.java, src/test/java/org/schemaspy/view/StyleSheetTest.java
Make it less coupled to MustacheWriter
For future create a factory instead of doing lots in constructor.
Minor fixes and complexity issues.
=> Stylesheet refactoring

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/view/DotFormatter.java, src/main/java/org/schemaspy/view/HtmlMultipleSchemasIndexPage.java, src/main/java/org/schemaspy/view/TextFormatter.java, src/main/resources/layout/tables/table.js
Fixes #412 
Also fixed minor sonarlint issues and new smells.
=> 412 view definition not readonly

src/test/java/org/schemaspy/testing/IgnoreUsingXPath.java, src/test/resources/integrationTesting/mssqlserver/expecting/mssqlserverhtmlit/htmlit.htmlit.xml
(reason why shadowing is bad)
* Updated xml for mssql related to #373
=> Made the evaluation look at the instance field

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/service/DatabaseService.java, src/main/java/org/schemaspy/util/Dot.java
=> 265 logging checkup

src/main/java/org/schemaspy/util/ConnectionURLBuilder.java
* Might be leftover from non-multischema time
* fixes #436
=> Removed deletion of remaining parameters

src/main/java/org/schemaspy/view/HtmlColumnsPage.java, src/main/java/org/schemaspy/view/HtmlTablePage.java, src/main/java/org/schemaspy/view/MustacheTableColumn.java, src/main/resources/layout/column.html, src/main/resources/layout/column.js, src/test/java/org/schemaspy/integrationtesting/PgSqlSuite.java, src/test/resources/integrationTesting/mssqlserver/expecting/mssqlserverhtmlit/columns.html, src/test/resources/integrationTesting/mysql/expecting/mysqlhtml/columns.html, src/test/resources/integrationTesting/mysql/expecting/mysqlmultischema/htmlit/columns.html
* Removed Indexed columns from MustashTableColumn since set/list not
needed
Small test and it seems it will be lot faster on large amount of columns, and a tiny bit slower on small amount of columns.
Fixes #162
=> Added data in columns page thru json object, deferedRender

src/main/java/org/schemaspy/view/DotNode.java, src/test/java/org/schemaspy/view/DotNodeIT.java
fixes #447
* https://www.graphviz.org/doc/info/shapes.html#html
* port is htmlDecoded before used in edges, so no need to escape in
DotConnector.
=> HtmlEscape text within dot label

src/main/resources/layout/column.html, src/main/resources/layout/constraint.html, src/main/resources/layout/main.html, src/main/resources/layout/routines.html, src/main/resources/layout/schemaSpy.js, src/main/resources/layout/tables/table.html, src/test/resources/integrationTesting/mssqlserver/expecting/mssqlserverhtmlit/columns.html, src/test/resources/integrationTesting/mssqlserver/expecting/mssqlserverhtmlit/index.html, src/test/resources/integrationTesting/mssqlserver/expecting/mssqlserverhtmlit/routines.html, src/test/resources/integrationTesting/mssqlserver/expecting/mssqlserverhtmlit/tables/group.html, src/test/resources/integrationTesting/mssqlserver/expecting/mssqlserverhtmlit/tables/group_resources.html, src/test/resources/integrationTesting/mssqlserver/expecting/mssqlserverhtmlit/tables/resources.html, src/test/resources/integrationTesting/mssqlserver/expecting/mssqlserverhtmlit/tables/user.html, src/test/resources/integrationTesting/mssqlserver/expecting/mssqlserverhtmlit/tables/userAndGroup.html, src/test/resources/integrationTesting/mysql/expecting/mysqlhtml/columns.html, src/test/resources/integrationTesting/mysql/expecting/mysqlhtml/constraints.html, src/test/resources/integrationTesting/mysql/expecting/mysqlhtml/index.html, src/test/resources/integrationTesting/mysql/expecting/mysqlhtml/routines.html, src/test/resources/integrationTesting/mysql/expecting/mysqlhtml/tables/group.html, src/test/resources/integrationTesting/mysql/expecting/mysqlhtml/tables/user.html, src/test/resources/integrationTesting/mysql/expecting/mysqlhtml/tables/userAndGroup.html, src/test/resources/integrationTesting/mysql/expecting/mysqlmultischema/htmlit/columns.html, src/test/resources/integrationTesting/mysql/expecting/mysqlmultischema/htmlit/constraints.html, src/test/resources/integrationTesting/mysql/expecting/mysqlmultischema/htmlit/index.html, src/test/resources/integrationTesting/mysql/expecting/mysqlmultischema/htmlit/routines.html, src/test/resources/integrationTesting/mysql/expecting/mysqlmultischema/htmlit/tables/group.html, src/test/resources/integrationTesting/mysql/expecting/mysqlmultischema/htmlit/tables/user.html, src/test/resources/integrationTesting/mysql/expecting/mysqlmultischema/htmlit/tables/userAndGroup.html
* Minor fixing in constraint.html
* Made left button group wider
* Updating test expectations
=> DataTableExportButtons will add div and button "group" is named

src/main/java/org/schemaspy/util/Html.java, src/main/java/org/schemaspy/view/DotNode.java, src/test/java/org/schemaspy/util/HtmlTest.java
* Reduced complexity and duplication
* Later we might want to do this a lot cleaner
=> Removed dependency to Mustache in DotNode

src/main/resources/layout/column.js
=> Render tablename as link in columnspage

pom.xml, src/test/java/org/schemaspy/integrationtesting/MssqlServerSuite.java, src/test/java/org/schemaspy/integrationtesting/OracleSpacesIT.java, src/test/java/org/schemaspy/integrationtesting/mssqlserver/MSSQLServerCheckConstraintIT.java, src/test/java/org/schemaspy/integrationtesting/mssqlserver/MSSQLServerCommentsIT.java, src/test/java/org/schemaspy/integrationtesting/mssqlserver/MSSQLServerHTMLIT.java, src/test/java/org/schemaspy/integrationtesting/mssqlserver/MSSQLServerRemoteTablesIT.java, src/test/java/org/schemaspy/testcontainer/OracleIT.java, src/test/java/org/testcontainers/containers/InformixContainer.java, src/test/resources/container-license-acceptance.txt
* Should provide better support for docker on windows
=> Bumped testcontainers-java

src/main/java/org/schemaspy/Main.java, src/main/java/org/schemaspy/logging/StackTraceOmitter.java, src/main/resources/META-INF/spring.factories, src/test/java/org/schemaspy/MainTest.java, src/test/java/org/schemaspy/integrationtesting/StackTraceOmitterIT.java, src/test/resources/logback-debugEx.xml
=> If StackTrace has been omitted, inform user of -debug arg.

src/main/java/org/schemaspy/SchemaSpyConfiguration.java, src/main/java/org/schemaspy/cli/CombinedDefaultProvider.java, src/main/java/org/schemaspy/cli/CommandLineArgumentParser.java, src/main/java/org/schemaspy/cli/DefaultProviderFactory.java, src/main/java/org/schemaspy/cli/EnvDefaultProvider.java, src/main/java/org/schemaspy/cli/PropertyFileDefaultProvider.java, src/test/java/org/schemaspy/cli/CombinedDefaultProviderTest.java, src/test/java/org/schemaspy/cli/EnvDefaultProviderTest.java, src/test/java/org/schemaspy/cli/PropertyFileDefaultProviderTest.java
* Combined will have search order that ends with EnvDefaultProvider
* If property file is available it will be used first
* No property file only env will be used
=> Replaced PropertyFileDefatulProvider with a CombinedDefaultProvider

src/main/resources/org/schemaspy/types/pgsql11.properties
* Only changes to routines sql
fixes #470
=> Added pgsql 11 properties

docs/source/configuration/commandline.rst, docs/source/index.rst, docs/source/sso.rst
=> Added single sign-on instructions for mssql and mssql-jtds

src/main/resources/layout/main.html, src/main/resources/layout/main.js, src/main/resources/layout/tables/table.html, src/test/java/org/schemaspy/view/HtmlMainIndexPageTest.java, src/test/java/org/schemaspy/view/HtmlTablePageTest.java, src/test/resources/integrationTesting/mssqlserver/expecting/mssqlserverhtmlit/tables/group.html, src/test/resources/integrationTesting/mssqlserver/expecting/mssqlserverhtmlit/tables/group_resources.html, src/test/resources/integrationTesting/mssqlserver/expecting/mssqlserverhtmlit/tables/resources.html, src/test/resources/integrationTesting/mssqlserver/expecting/mssqlserverhtmlit/tables/user.html, src/test/resources/integrationTesting/mssqlserver/expecting/mssqlserverhtmlit/tables/userAndGroup.html, src/test/resources/integrationTesting/mysql/expecting/mysqlhtml/tables/group.html, src/test/resources/integrationTesting/mysql/expecting/mysqlhtml/tables/user.html, src/test/resources/integrationTesting/mysql/expecting/mysqlhtml/tables/userAndGroup.html, src/test/resources/integrationTesting/mysql/expecting/mysqlhtmlsvg/tables/group.html, src/test/resources/integrationTesting/mysql/expecting/mysqlhtmlsvg/tables/user.html, src/test/resources/integrationTesting/mysql/expecting/mysqlhtmlsvg/tables/userAndGroup.html, src/test/resources/integrationTesting/mysql/expecting/mysqlmultischema/htmlit/tables/group.html, src/test/resources/integrationTesting/mysql/expecting/mysqlmultischema/htmlit/tables/user.html, src/test/resources/integrationTesting/mysql/expecting/mysqlmultischema/htmlit/tables/userAndGroup.html
=> 486 norows hide row info

src/test/java/org/schemaspy/testing/XmlOutputDiff.java, src/test/java/org/schemaspy/view/MustacheCompilerTest.java
=> 512 failing diff test

src/test/java/org/schemaspy/service/TableServiceConnectForeignKeysTest.java, src/test/java/org/schemaspy/service/TableServiceConnectTest.java, src/test/java/org/schemaspy/testing/ConfigRule.java
* Corrected ConfigRule
* Renamed ConnectTest to much Test in name
=> Added connectForeignKeyTest for TableService

.gitignore, src/test/resources/integrationTesting/mssqlserver/expecting/mssqlserverhtmlit/relationships.html
* Added jenv local config file to .gitignore
=> Fixed tests after corretion in #531

docs/source/configuration/databaseType.rst
=> Fix a typo in documentation

src/main/java/org/schemaspy/input/dbms/service/IndexService.java
=> Close PreparedStatements in IndexService

src/main/resources/org/schemaspy/types/db2i.properties
Hi,
I missed routines support in #563, so here it is.
=> Adding routines support for DB2 for i (former AS/400)

docs/source/configuration/commandline.rst, docs/source/new.rst, src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/cli/CommandLineArguments.java, src/main/java/org/schemaspy/cli/DegreeOfSeparationValidator.java, src/main/java/org/schemaspy/output/html/mustache/diagrams/MustacheTableDiagramFactory.java, src/main/resources/commandlinearguments.properties, src/test/java/org/schemaspy/cli/CommandLineArgumentParserTest.java, src/test/java/org/schemaspy/cli/DegreeOfSeparationValidatorTest.java, src/test/java/org/schemaspy/output/html/mustache/diagrams/MustacheTableDiagramFactoryTest.java
Squashed #481 and made changes more or less as commented by me.
If this is acceptable it will replace #481
=> Limit degree of separation

pom.xml, src/main/java/org/schemaspy/Config.java
* Added some javadoc before I realized it was too much, disabled javadoc
=> Bumping plugin versions and adding release plugin

src/main/java/org/schemaspy/output/dot/schemaspy/DotNode.java, src/test/java/org/schemaspy/output/dot/schemaspy/DotNodeTest.java
* Also made DetailedSize skipped if null
Fixes #599
=> HtmlEscape both ShortType and DetailedSize

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/output/diagram/graphviz/GraphvizDot.java, src/test/java/org/schemaspy/output/diagram/graphviz/GraphvizDotTest.java, src/test/resources/dotFakes/2.32.0/bin/dot
* Didn't parse possible renderers correctly
* Fixes #611
=> Renderer in config never read

.dockerignore, .travis.yml, Dockerfile, docker.sh, docker/entrypoint.sh, docker/schemaspy.sh, src/main/java/org/schemaspy/output/diagram/graphviz/GraphvizDot.java
* Possible to override /output with ENV: OUTPUT
* Possible to override /drivers with ENV: DRIVERS
* Removed volumes
Fixes #583
=> Clean up docker

src/main/java/org/schemaspy/output/dot/schemaspy/DotNode.java
Because i forgot to add  my name as an Editor to the .java file here is the pull-req, if it is ok.
=> Just Added My Name to the DotNode.java that got changed

Dockerfile, docker/schemaspy.sh
* This is as requested in comments to #601
=> Prefixed output and drivers ENVs for docker

src/main/resources/layout/tables/table.js
=> Correcting missing $ in backreference

src/main/java/org/schemaspy/input/dbms/service/DatabaseService.java, src/main/resources/org/schemaspy/types/informix.properties, src/test/java/org/schemaspy/testcontainer/InformixCheckConstraintIT.java, src/test/resources/integrationTesting/informixIndexXMLIT/dbScripts/informixcc.sql
* Informix checkconstraint query
* multirowdata flag in databaseType
* fixes #637
=> Support for append in CheckConstraints

pom.xml, travis.sh
* Removed debug flag.
* Specified report output jacoco
* Specified report input sonar
=> Update to use JacocoXMLReport instead of exec

src/main/java/org/schemaspy/input/dbms/service/RoutineService.java, src/main/java/org/schemaspy/util/CaseInsensitiveMap.java, src/main/java/org/schemaspy/view/HtmlConstraintsPage.java, src/main/resources/org/schemaspy/types/informix.properties, src/test/java/org/schemaspy/testcontainer/InformixIndexXMLIT.java, src/test/java/org/schemaspy/testcontainer/InformixRoutinesIT.java, src/test/java/org/schemaspy/testing/IgnoreNonPrintedInCData.java, src/test/resources/integrationTesting/informixIndexXMLIT/dbScripts/informixroutines.sql, src/test/resources/integrationTesting/informixIndexXMLIT/expecting/test.informix.xml
* Added append capabilities to RoutineService
* Added merge to CaseInsensitiveMap
* Trim for data added in ConstraintPage and RoutinePage
* Trimming of texts since they seem to be same size as column when fetching instead of all places.
* Ignore whitespaces and line breaks in CDATA section
* fixes #648
=> Routines for Informix

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/view/FileNameGenerator.java, src/main/java/org/schemaspy/view/MustacheCompiler.java, src/main/resources/layout/routines.html, src/test/java/org/schemaspy/view/FileNameGeneratorTest.java
* Will have first chars from name and at end append _ + hashcode of name in hex.
* This should probably be used in more places, this code also be extended to remove illegal chars
* fixes #654
=> Generate name if name is longer than 40

src/main/resources/org/schemaspy/types/pgsql.properties, src/main/resources/org/schemaspy/types/pgsql11.properties, src/test/java/org/schemaspy/integrationtesting/pgsql/PgSqlPloyFuncIT.java, src/test/resources/integrationTesting/pgsql/dbScripts/polyfunc.sql
=> Added arguments to routine name

src/main/resources/org/schemaspy/types/informix.properties, src/test/resources/integrationTesting/informixIndexXMLIT/expecting/test.informix.xml
=> Corrected SQL to get correct return types

src/main/java/org/schemaspy/output/xml/dom/XmlRoutineFormatter.java, src/test/java/org/schemaspy/output/xml/dom/XmlRoutineFormatterTest.java, src/test/resources/integrationTesting/informixIndexXMLIT/expecting/test.informix.xml, src/test/resources/integrationTesting/mysql/expecting/mysqlhtml/htmlit.htmlit.xml, src/test/resources/integrationTesting/mysql/expecting/mysqlhtml_gv_svg/htmlit.htmlit.xml, src/test/resources/integrationTesting/mysql/expecting/mysqlhtml_vizjs_svg/htmlit.htmlit.xml
=> Added routine parameters to xml output

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/input/dbms/service/DbmsService.java, src/main/java/org/schemaspy/view/SqlAnalyzer.java, src/test/java/org/schemaspy/view/SqlAnalyzerTest.java, src/test/resources/integrationTesting/mssqlserver/expecting/mssqlserverhtmlit/tables/userAndGroup.html
* also added the one returned from DatabaseMetaData
* fixes #641
=> Improved SqlAnalyzer added mssql identifiers `[]`

src/main/resources/org/schemaspy/types/mssql17-jtds.properties, src/main/resources/org/schemaspy/types/mssql17.properties, src/test/java/org/schemaspy/integrationtesting/MssqlServerSuite.java, src/test/java/org/schemaspy/integrationtesting/mssqlserver/MSSQLServerCheckConstraintIT.java, src/test/java/org/schemaspy/integrationtesting/mssqlserver/MSSQLServerCommentsIT.java, src/test/java/org/schemaspy/integrationtesting/mssqlserver/MSSQLServerHTMLIT.java, src/test/java/org/schemaspy/integrationtesting/mssqlserver/MSSQLServerRemoteTablesIT.java, src/test/resources/container-license-acceptance.txt
* This works with 2017 and 2019
* Hopefully queries work with Azure
* fixes #640
=> Added updated queries for MSSQL

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/output/dot/schemaspy/DotNode.java, src/main/java/org/schemaspy/view/MustacheTableColumnRelatives.java, src/main/resources/layout/multi.html, src/test/resources/integrationTesting/mysql/expecting/mysqlmultischema/index.html
Do filename handling when doing multiple schema analysis
Added `'` around schema names in multiple schema analysis
=> 644 schema name in all

docs/source/configuration/commandline.rst
I tried to use the option and I think the description could be a little bit extended
=> -meta fileOrPath description extended

docs/source/advanced_usage.rst, docs/source/databases/index.rst, docs/source/databases/mssql.rst.inc, docs/source/faq.rst, docs/source/index.rst
* Fixed some minor warnings in FAQ and advanced_usage
=> Added Databases to TOC and subpage MSSQL with SSO

docs/source/configuration/databaseType.rst, src/main/java/org/schemaspy/input/dbms/service/ColumnLabel.java, src/main/java/org/schemaspy/input/dbms/service/ViewService.java
* Added multirowdata, selectViewCommentsSql, selectViewColumnCommentsSql
* Minor fixes in ViewService (added fields to ColumnLabel
fixes #724
=> 724 Document Sql overrides

pom.xml
=> fix(build): surefire, failsafe, jacoco argLine

src/main/java/org/schemaspy/Config.java
=> chore: deprecate config.java

src/main/resources/org/schemaspy/types/sqlite-xerial.properties
=> chore: sqlite-xerial open read_only

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/cli/CommandLineArguments.java, src/main/java/org/schemaspy/output/diagram/graphviz/GraphvizConfig.java, src/main/java/org/schemaspy/output/diagram/graphviz/GraphvizConfigCli.java, src/main/java/org/schemaspy/output/diagram/graphviz/GraphvizDot.java, src/main/resources/graphvizconfigcli.properties, src/test/java/org/schemaspy/output/diagram/graphviz/GraphvizDotTest.java, src/test/java/org/schemaspy/output/dot/schemaspy/DotNodeIT.java
* move from Config.java to JCommander
* fix #859
=> GraphvizConfig

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/output/html/mustache/diagrams/MustacheSummaryDiagramFactory.java, src/main/java/org/schemaspy/output/html/mustache/diagrams/MustacheSummaryDiagramResults.java, src/main/java/org/schemaspy/output/html/mustache/diagrams/MustacheTableDiagramFactory.java, src/test/java/org/schemaspy/output/html/mustache/diagrams/MustacheSummaryDiagramFactoryTest.java, src/test/java/org/schemaspy/output/html/mustache/diagrams/MustacheTableDiagramFactoryTest.java, src/test/java/org/schemaspy/view/HtmlRelationshipsPageTest.java
=> 885 remove unused writestats

src/main/java/org/schemaspy/output/diagram/DiagramFactory.java, src/main/java/org/schemaspy/output/diagram/DiagramResult.java, src/main/java/org/schemaspy/output/html/mustache/diagrams/MustacheOrphanDiagramFactory.java, src/main/java/org/schemaspy/output/html/mustache/diagrams/MustacheSummaryDiagramFactory.java, src/main/java/org/schemaspy/output/html/mustache/diagrams/MustacheTableDiagramFactory.java, src/main/java/org/schemaspy/view/MustacheTableDiagram.java, src/test/java/org/schemaspy/output/html/mustache/diagrams/MustacheSummaryDiagramFactoryTest.java, src/test/java/org/schemaspy/output/html/mustache/diagrams/MustacheTableDiagramFactoryTest.java, src/test/java/org/schemaspy/view/MustacheTableDiagramTest.java
* Singular
* More inline with MustacheTableDiagram
=> chore: refactor DiagramResults

src/main/java/org/schemaspy/output/diagram/graphviz/GraphvizDot.java
This fixes the cause for #944, but a release needs to be made.
Test the regex here: https://regexr.com/6q6es
=> Fix the version regex for graphviz

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/input/dbms/ConnectionURLBuilder.java, src/main/java/org/schemaspy/input/dbms/DbDriverLoader.java, src/main/java/org/schemaspy/input/dbms/service/SqlService.java
Enables SchemaSpy to respect `--database-type`
=> #1004/database type

src/main/java/org/schemaspy/input/dbms/DbDriverLoader.java, src/test/java/org/schemaspy/input/dbms/DbDriverLoaderTest.java, src/test/java/org/schemaspy/integrationtesting/oracle/OracleSpacesIT.java
=> chore(DbDriverLoader): use commandLineArgs for user instead of config

README.md, docs/.gitignore, docs/source/_ext/schemaspy_database_types.py, docs/source/_static/css/clean_table.css, docs/source/conf.py, docs/source/configuration/databaseType.rst
=> 971 docs db types

.readthedocs.yaml, README.md, docs/requirements.txt
* config file for read the docs
* requirements.txt for docs
* updated instructions
=> chore(docs): read the docs requirements

.github/workflows/development.yml, pom.xml
* add aggregated report unit+integration
* new profile for coverage -P coverage
* update workflow to add new profile
=> chore(coverage): split sonar and coverage

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/input/dbms/ConnectionURLBuilder.java, src/test/java/org/schemaspy/ConfigTest.java, src/test/java/org/schemaspy/input/dbms/ConnectionURLBuilderTest.java
=> chore(config): remove determineDbProperties

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/cli/CommandLineArguments.java, src/main/java/org/schemaspy/connection/PreferencesConnection.java, src/main/java/org/schemaspy/input/dbms/DbDriverLoader.java, src/main/resources/commandlinearguments.properties, src/test/java/org/schemaspy/cli/CommandLineArgumentParserTest.java
fixes #978 Config.pullParam consumes, so can only be read once, CommandLineArguments will store it
=> fix(connprops): move to CommandLineArguments

src/main/java/org/schemaspy/cli/CommandLineArguments.java, src/main/java/org/schemaspy/output/diagram/graphviz/GraphvizConfigCli.java, src/test/java/org/schemaspy/cli/CommandLineArgumentParserTest.java
=> fix(cli): remove single word parameter names

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/SimpleRuntimeDotConfig.java, src/main/java/org/schemaspy/output/dot/RuntimeDotConfig.java, src/main/java/org/schemaspy/output/dot/schemaspy/DotConfigHeader.java, src/main/java/org/schemaspy/output/dot/schemaspy/DotFormatter.java, src/main/java/org/schemaspy/output/dot/schemaspy/DotNode.java, src/main/java/org/schemaspy/output/dot/schemaspy/DotSummaryFormatter.java, src/main/java/org/schemaspy/output/dot/schemaspy/DotTableFormatter.java, src/main/java/org/schemaspy/output/dot/schemaspy/OrphanGraph.java, src/main/java/org/schemaspy/output/dot/schemaspy/relationship/ImpliedRelationships.java, src/main/java/org/schemaspy/output/dot/schemaspy/relationship/RealRelationships.java, src/test/java/org/schemaspy/integrationtesting/SchemaMetaIT.java, src/test/java/org/schemaspy/output/dot/schemaspy/DotConfigHeaderTest.java, src/test/java/org/schemaspy/output/dot/schemaspy/DotNodeTest.java, src/test/java/org/schemaspy/output/dot/schemaspy/OrphanGraphTest.java
* interface contains things that are set during runtime
=> chor(dotconfig): rename to RuntimeDotConfig

src/main/java/org/schemaspy/cli/CommandLineArguments.java, src/main/java/org/schemaspy/cli/TemplateDirectoryConfigCli.java, src/main/java/org/schemaspy/view/HtmlConfigCli.java, src/main/resources/htmlconfigcli.properties, src/main/resources/templatedirectorycli.properties
* templatedirectory is shared with other configuration
=> chore(htmlconfigcli): extract templateDirectory

.github/workflows/development.yml, pom.xml
* add snapshot repository to pom
* include deploy in test and build
* remove deploy step
=> fix(ghp): deploy to GitHub Packages

docs/source/installation.rst
* moved JDBC up one level
* moved prerequisits down under an application header
* moved Docker to top level of installation
* updated bleeding edge link
=> chore(docs): changed order

.github/workflows/rebuild_and_upload.yml, .github/workflows/release.yml
* add fallback to build and upload
=> fix(workflow): fix release workflow

Dockerfile
Specify the filename and don't rely on remote name
=> fix(docker): included drivers

src/main/resources/layout/anomalies.html, src/main/resources/layout/constraint.html, src/main/resources/layout/main.html, src/main/resources/layout/multi.html, src/main/resources/layout/routines.html, src/main/resources/layout/tables/table.html, src/test/java/org/schemaspy/view/HtmlRoutinesPageTest.java
=> fix(links): send raw values to toFileName

src/main/java/org/schemaspy/cli/CommandLineArgumentParser.java, src/main/java/org/schemaspy/cli/ConfigFileArgument.java, src/main/resources/configfileargument.properties
only so that it's show in usage
=> fix(cli): add ConfigFileArgument to parser

docs/source/configuration/commandline.rst, src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/cli/CombinedDefaultProvider.java, src/main/java/org/schemaspy/cli/CommandLineArguments.java, src/main/java/org/schemaspy/output/dot/schemaspy/DotFormatter.java, src/main/java/org/schemaspy/output/dot/schemaspy/DotSummaryFormatter.java, src/main/resources/commandlinearguments.properties, src/test/java/org/schemaspy/integrationtesting/SchemaMetaIT.java, src/test/java/org/schemaspy/integrationtesting/mssqlserver/MSSQLServerHTMLIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlHTMLIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlHTMLRemoteRelationshipsIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlIllegalFileNameCharsInTableNameIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlMultiSchemaIT.java
=> #763 orphans

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/input/dbms/service/DatabaseService.java, src/main/java/org/schemaspy/model/Console.java
Logging is done both in and outside of ProgressListener.
Moved logging inside of ProgressListener.
=> fix(progress): remove redundant logging

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/progress/Condition.java, src/main/java/org/schemaspy/progress/ConditionalProgress.java, src/main/java/org/schemaspy/progress/FinishCallback.java, src/main/java/org/schemaspy/progress/IfUpdateAfter.java, src/main/java/org/schemaspy/progress/Job.java, src/main/java/org/schemaspy/progress/Proc.java, src/main/java/org/schemaspy/progress/Progress.java, src/main/java/org/schemaspy/progress/ProgressReporter.java, src/test/java/org/schemaspy/progress/ConditionalProgressTest.java, src/test/java/org/schemaspy/progress/IfUpdateAfterTest.java, src/test/java/org/schemaspy/testing/ControlledInstanceSource.java
* Implemented for Routines pages
=> chore(progress): progress library

src/main/java/org/schemaspy/Main.java, src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/input/dbms/service/SqlService.java, src/test/java/org/schemaspy/input/dbms/service/DatabaseServiceTest.java, src/test/java/org/schemaspy/output/html/mustache/diagrams/MustacheSummaryDiagramFactoryTest.java, src/test/java/org/schemaspy/output/html/mustache/diagrams/MustacheTableDiagramFactoryTest.java, src/test/java/org/schemaspy/output/html/mustache/diagrams/OrphanDiagramTest.java, src/test/java/org/schemaspy/view/HtmlOrphansPageTest.java
=> chore: remove unused imports

docs/source/configuration/commandline.rst, src/main/java/org/schemaspy/input/dbms/ProcessingConfig.java, src/main/java/org/schemaspy/input/dbms/ProcessingConfigCli.java, src/main/java/org/schemaspy/input/dbms/service/DatabaseServiceFactory.java, src/main/java/org/schemaspy/input/dbms/service/RoutineService.java, src/main/resources/processingconfigcli.properties, src/test/java/org/schemaspy/integrationtesting/informix/InformixIndexXMLIT.java, src/test/java/org/schemaspy/integrationtesting/informix/InformixRoutinesIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlHTMLGvSvgIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlHTMLIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlHTMLRemoteRelationshipsIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlHTMLVizJsIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlMultiSchemaIT.java, src/test/resources/integrationTesting/mysql/expecting/mysqlhtmlillegal/illegal.illegal.xml, src/test/resources/integrationTesting/mysql/expecting/mysqlhtmlillegal/routines/___det_4e5ade89.html
Implements feature request 1168
Redacting routine definition by default to avoid information disclosure. This requires users to actively include it.
=> 1168 routine definition

README.md
=> Add note about JAR types

src/main/resources/org/schemaspy/types/db2.properties, src/main/resources/org/schemaspy/types/firebird.properties, src/main/resources/org/schemaspy/types/h2.properties, src/main/resources/org/schemaspy/types/hive.properties, src/main/resources/org/schemaspy/types/hsqldb.properties, src/main/resources/org/schemaspy/types/informix.properties, src/main/resources/org/schemaspy/types/mariadb.properties, src/main/resources/org/schemaspy/types/maxdb.properties, src/main/resources/org/schemaspy/types/mssql-jtds.properties, src/main/resources/org/schemaspy/types/mssql.properties, src/main/resources/org/schemaspy/types/mssql05.properties, src/main/resources/org/schemaspy/types/mysql.properties, src/main/resources/org/schemaspy/types/netezza.properties, src/main/resources/org/schemaspy/types/ora.properties, src/main/resources/org/schemaspy/types/pgsql.properties, src/main/resources/org/schemaspy/types/sqlite-xerial.properties, src/main/resources/org/schemaspy/types/sqlite.properties, src/main/resources/org/schemaspy/types/sybase.properties, src/main/resources/org/schemaspy/types/sybase2.properties, src/main/resources/org/schemaspy/types/sybase3.properties, src/main/resources/org/schemaspy/types/teradata.properties
=> chore: remove driverPath from databaseType properties

src/main/java/org/schemaspy/output/html/mustache/diagrams/MustacheSummaryDiagramFactory.java
* complete try-with-resource before resource is used by external application
=> fix: close before use

pom.xml
* create additional jar for application with logback.xml
* modify default jar to exclude logback.xml
=> fix: exclude logback.xml from library jar
