.gitignore, src/main/java/org/schemaspy/DbAnalyzer.java
Reverts schemaspy/schemaspy#19
Reverse back changes from Merge pull request #19 from ismailsimsek/impliedrel
implied relationship fix
Unfortunately something is not working as should, for my large database I have to many implied relationship. To many  implied relationship also prolonged total time of diagram generation from few minutes to several dozen minutes.
Today to master branch I will commit new version of SchemaSpy with DbAnalyzerTest for cover test  DbAnalyzer.getImpliedConstraints. If in your opinion current solution is working incorrectly please prepare test with your data and be sure that changes made by you covering also existing testes.
=> Revert "implied relationship fix"

src/main/java/org/schemaspy/service/SqlService.java, src/main/java/org/schemaspy/util/ConnectionURLBuilder.java, src/main/java/org/schemaspy/util/DbSpecificOption.java, src/test/java/org/schemaspy/util/DbSpecificOptionTest.java
Remove the second unused constructor and change the type of the 'value'
field to String as it cannot be any other Object by now. The other changes are mainly code style changes.
As #getValue returns only String then the callers do not need to call
toString on the returned values.
_(I used IntelliJ IDEA 2016.3.2 Build #IU-163.10154.41)_
=> Refactoring of DBSpecificOption

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/Main.java, src/main/java/org/schemaspy/service/SqlService.java
#42 
In this case close shouldn't be called in finally block.
=> `-all` flag causes schemaspy to always exit non-zero code

src/main/java/org/schemaspy/Config.java
WARNING exception in DbAnalyzerTest when schemaspy.properties is missing #46
=> WARNING exception in DbAnalyzerTest when schemaspy.properties is missing #46

pom.xml, src/test/java/org/schemaspy/DbAnalyzerTest.java
In preparation to extend the test coverage of the project this commit
introduces AssertJ as a support to write tests in a fluent way.
As an example I replaced the JUnit-addons dependency and the usage of
its ListAssert method in the DBAnalyzerTest. I combined the two
assertions where the first one checked the list for emptyness, as this is
already included in the second assertion (containsExactly...).
I also removed the inheritance of TestCase as it is obsolete since JUnit
4.
=> Introduce AssertJ as test dependency, remove JUnit-addons, Refactoring

src/main/resources/org/schemaspy/types/mariadb.properties
This is pull request extend SchemaSpy for MariaDB support configuration file. Fix MariaDB 5.5.x support? #71
Connection was tested used [MariaDB Connector/J 1.5.9](https://downloads.mariadb.org/connector-java/1.5.9/)
You can two option for prepare the configuration for MariaDB using schemaspy.properties file:
```
schemaspy.t=mariadb
schemaspy.dp=\drivers\mariadb-java-client-1.5.9.jar
schemaspy.host=localhost
schemaspy.port=3306
schemaspy.db=database_name
schemaspy.u=root
schemaspy.p=password
schemaspy.o=\doc\schemaspy\output
schemaspy.charset=UTF-8
```
Configuration by command line parameters:
`java -jar schemaspy.jar -t mariadb -dp \drivers\mariadb-java-client-1.5.9.jar -db dbName -host localhost -port 3306 -u root -p password -o \doc\schemaspy\output -charset=UTF-8`
=> Maria DB 5.5 support

.travis.yml
After this change each time when pull request will be merged to the master user can download new SchemaSpy jar version for tests purposes before release.
=> add travis deploy for master build

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/DbDriverLoader.java, src/main/resources/org/schemaspy/types/impala.properties
This PR improve SchemaSpy to support impala database #64 
Impala JDBC driver is quite specific to use this driver with SchemaSpy to the class path more external jars must be added.
You can read more about this here on Cloudera Impala page https://www.cloudera.com/documentation/enterprise/5-9-x/topics/impala_jdbc.html#jdbc_setup
To use impala JDBC driver please set  `-loadjars=true` if enabled SchemaSpy will load to the JAVA classpath additional jars used by JDBC Driver
=> Impala support

pom.xml
The declaration of the mockito dependency was missing the scope and
therefore was falling back to 'compile' scope. This caused the Maven
build to include the transitive dependency 'byte-buddy' in the generated
SchemaSpy jar file.
=> Set scope 'test' for mockito dependency, remove duplicate scope [enhancement]

docker/release/Dockerfile, docker/release/entrypoint.sh, docker/release/readme.md, docker/snapshot/Dockerfile
They current don't contain any jdbc-drivers.
* Release contains a small entry script since we have changed the main-class since rc1.
* Release will download the github release artifact.
* Will git clone the repository and build it.
=> Docker image builds: snapshot and relase

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/view/MustacheWriter.java, src/main/java/org/schemaspy/view/StyleSheet.java
issue #26
I'm still not quite sure if the behaviour is correct as intended.
Here's what I observerd so far regarding the priority of used css file:
Given command line argument `-css my.css` (default: `schemaSpy.css`):
1.  look for css file in same folder as jar
2.  look for css file in template directory (default '`layout`')
3.  look for css file in user.dir (home dir)
4.  use internal css file in classpath/schemaspy jar file (`src/main/resources/layout`)
@rafalkasa please take a look if this is how it is supposed to be.
=> Fix use of -css command line argument. Remove unused method Config#isJarFile

README.md
The old link is redirected to sonarcloud.io but cannot find the
SchemaSpy project. Fails with the message
"Component key 'org.schemaspy%3Aschemaspy' not found"
=> Fix link to SonarQube project in README.md

pom.xml, src/test/java/org/schemaspy/testcontainer/OracleIT.java
The helper library is currently hosted on my bintray but it's public so no worries, I was supposed to be synched to jcenter and I'm looking into getting it on maven central.
All drivers located in ext-lib will be added to classpath for tests in verify phase.
=> Removed usage of fork and added a helper library

Dockerfile, docker.sh
fixes #122 
This might break if openjdk remove the 8u111 image.
To avoid it we could.....copy the dockerfile for 8u111 and just add our stuff in the end.
=> Pinned jre to 8u111, added branch,revision,driver versions as labels

src/main/resources/org/schemaspy/types/db2net.properties, src/main/resources/org/schemaspy/types/db2zosnet.properties
Changed the package of the db2net Driver.
Added a db2zosnet.properties to get a jdbc type 4 access to a db2z-database.
=> Added JDBC Type 4 Driver Access to DB2/zos

src/main/java/org/schemaspy/view/HtmlTablePage.java, src/main/java/org/schemaspy/view/MustacheWriter.java, src/main/resources/layout/container.html
This PR add contextual information to the tables pages for example ABC table page will have a title like <title>ABC table - XYZ Database</title>.
This PR fix issue #136
=> Add table name in to HTML title tag

src/main/java/org/schemaspy/view/HtmlMainIndexPage.java, src/main/resources/layout/main.html
This pull request is covering backward compatibility with SchemaSpy 5.0.x after information provided after `-desc` parameter will be visible on main page fix #149
`-desc "<b>Connection details:</b></br><b>Host/Port: </b>127.0.0.1:1433</br><b>DBName: </b>Librrary</br>"`
=> Display on main page database description in HTML

src/main/java/org/schemaspy/view/HtmlColumnsPage.java, src/main/java/org/schemaspy/view/HtmlConstraintsPage.java, src/main/resources/layout/column.html, src/main/resources/layout/column.js, src/main/resources/layout/constraint.html, src/main/resources/layout/constraint.js, src/main/resources/layout/main.html, src/main/resources/layout/main.js
#162 - Add pagination to both the column and constraint pages
Follow the setting used on the main table listing page
Tested on a database with ~800 tables, ~9,000 columns, and ~600 constraints.
I do wonder if adding pagination controls to the top in addition to the bottom would be helpful. See https://datatables.net/examples/advanced_init/dom_multiple_elements.html for an example
Initial rendering of the column page is still slow due to how datatables works. It still has to render all of the rows and then hide them. So, this might not fully solve #162
=> #162 - Add pagination

src/main/java/org/schemaspy/view/DotNode.java, src/main/java/org/schemaspy/view/HtmlFormatter.java, src/test/java/org/schemaspy/view/HtmlFormatterTest.java
This is a possible fix for #165 .
Tested against a SQLServer database with a table with spaces in the name, requiring the table to be wrapped in square brackets.
There is a difference between URL encoding, and escaping for HTML. The only place this code is used is in the DOT generation, and then would only affect image map generation, and maybe SVGs (if those were to be built from the DOT files). I've changed the code so that the tooltip is HTML Encoded, and the link elements are URL-escaped, with `%20` for spaces instead of `+`. Also, added tests.
I used a utility method from inside Mustache to do the escaping. There are similar utility methods in commons-lang, guava, and some Spring libraries, but none of those are on the production profile (an older commons-lang is only present in the …
=> Add tests for HtmlFormatter, fix URL encoding issue in maps

src/main/resources/layout/container.html, src/main/resources/layout/tables/table.js
The code element is not rendered for tables, just for views. So, initializing codemirror should check for the presence of the code element. This was causing errors to appear in the browser console.
Also, I noticed that the favicon was not loading on table pages. This was fixed by including the relative path to `favicon.png`, just like all of the other resources in `container.html`
Fixes #172
=> Don't init codemirror when there is no code element

src/main/resources/org/schemaspy/types/mssql.properties, src/main/resources/org/schemaspy/types/mssql05.properties
This will only work on SQLServer 2012 and later.
Discussion - should we create a separate properties file for `mssql2012`, or just raise the baseline?
=> Support Routines in SQLServer

src/main/java/org/schemaspy/DbAnalyzer.java, src/test/java/org/schemaspy/DbAnalyzerTest.java
If I use schemaspy 6.0.0-rc2 and have a table with a clumn named '{AccountBuyingKey}' I get the exception below. The following pullrequest fixes that by using Pattern.quote on all literal strings used in regex matching.
Illegal repetition near index 6
(?i).*_{AccountBuyingKey}
^
java.util.regex.PatternSyntaxException: Illegal repetition near index 6
(?i).*_{AccountBuyingKey}
^
at java.util.regex.Pattern.error(Pattern.java:1955)
at java.util.regex.Pattern.closure(Pattern.java:3157)
at java.util.regex.Pattern.sequence(Pattern.java:2134)
at java.util.regex.Pattern.expr(Pattern.java:1996)
at java.util.regex.Pattern.compile(Pattern.java:1696)
at java.util.regex.Pattern.<init>(Pattern.java:1351)
at java.util.regex.Pattern.compile(Pattern.java:1028)
at …
=> Escape column names in regexp sot that columns can contain charaters '{' and '}'.

src/main/resources/org/schemaspy/types/mssql.properties, src/main/resources/org/schemaspy/types/mssql12-jtds-instance.properties, src/main/resources/org/schemaspy/types/mssql12-jtds.properties, src/main/resources/org/schemaspy/types/mssql12.properties
Per our discussion in #182, this moves the support for querying routines to a new database type - mssql12.
This also adds support for routines to the JDTS driver
* mssql12 extends mssql05 extends mssql
* mssql12-jtds extends mssql05-jtds extends mssql-jtds
* mssql12-jtds-instance extends mssql05-jtds-instance extends mssql-jtds-instance
=> Move Routines support for SQLServer into new type - mssql12

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/DbAnalyzer.java, src/main/java/org/schemaspy/service/DatabaseService.java, src/main/java/org/schemaspy/service/SqlService.java, src/main/java/org/schemaspy/service/TableService.java, src/main/java/org/schemaspy/service/ViewService.java, src/main/java/org/schemaspy/util/DiagramUtil.java, src/main/java/org/schemaspy/util/Markdown.java, src/main/java/org/schemaspy/view/XmlTableFormatter.java
Fix the following Sonar issues to try and get the quality up a little bit (and learn the codebase in the process)
* Removed a dead store (1 occurrence)
* Use isEmpty() to check whether the collection is empty or not. (4 occurrences)
* ...  returns a string, there's no need to call "toString()". (6 occurrences)
* Use try-with-resources for Statements and ResultSets. There were a few different patterns to how these were being closed - sometimes null checked without try-catch around the close, sometimes in the wrong order (statement then resultset), sometimes they were not null checked, and sometimes with a stacktrace being printed.
* There were a couple of `while ... break` loops that executed at most one time. Changed these to `if` blocks. This was an Intellij warning.
I debated …
=> Fix some sonar warnings, consistent use of try-with-resource for SQL

src/main/java/org/schemaspy/model/Database.java, src/main/java/org/schemaspy/service/InconsistencyException.java, src/main/java/org/schemaspy/service/TableService.java, src/main/resources/org/schemaspy/types/hive.properties
* We have an SQL92 keywords list, so we don't need to fail if we can't
get from database
* If we can't retrieve column from table model using ResulSetMetaData
check if it contains table/fulltable name in the MetaData and strip it.
If it's still not found throw an InconsistencyException (this is for
when DatabaseMetaData returns columns in one way and ResultSetMetaData
in another.
* Added basic hive dbtype connectionSpec/connectionString has a bunch of
options: https://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.3.0/bk_dataintegration/content/hive-jdbc-odbc-drivers.html
=> More relaxed handling on missing Database/ResultSetMetadata

mvnw.cmd, src/test/java/org/schemaspy/util/DotTest.java
* mvnw.cmd had a comment using # which is invalid for windows @REM is used
* DotTest works only on linux, everything executes from shell or have the #!
instruction, it doesn't work the same way on windows, and it would require
a modification in Dot.java to be able to use a shim as we do in the test.
=> added @REM to mvnw to '#', made DotTest only run on linux

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/cli/PropertyFileDefaultProvider.java, src/main/java/org/schemaspy/util/DiagramUtil.java, src/main/java/org/schemaspy/util/Dot.java, src/main/java/org/schemaspy/util/ResourceWriter.java, src/main/java/org/schemaspy/view/HtmlOrphansPage.java, src/main/java/org/schemaspy/view/HtmlTablePage.java
There are several Sonar warnings around "Do something with the "boolean" value returned by "delete"".
HtmlTablePage.java in particular attempts to delete all of the files that will be generated, but doesn't check to see if they were actually deleted. Its possible that the files could be locked by another process.
A couple different changes were made, trying to keep with the intent of the original code while providing better error handling.
* [FileUtils.forceMkdir](https://github.com/apache/commons-io/blob/master/src/main/java/org/apache/commons/io/FileUtils.java#L2474) - Will throw an exception if the input already exists but is not a directory, otherwise attempts to call mkdirs. If that fails, throws an IOException
* Files.deleteIfExists - deletes a file if it exists, throws an …
=> Clean up Sonar warnings around File deletion

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/output/OutputException.java, src/main/java/org/schemaspy/output/OutputProducer.java, src/main/java/org/schemaspy/output/xml/XmlProducer.java, src/main/java/org/schemaspy/output/xml/XmlProducerException.java, src/main/java/org/schemaspy/output/xml/dom/DOMUtil.java, src/main/java/org/schemaspy/output/xml/dom/XmlProducerUsingDOM.java, src/main/java/org/schemaspy/output/xml/dom/XmlTableFormatter.java
Moving xml generation out of SchemaAnalyzer.
Making it possible to add more OutputProducers.
It can now easily be replaced with an alternative to DOM or even add json if that is something one would like.
=> Moving xml generation separate package

pom.xml, src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/DbAnalyzer.java, src/main/java/org/schemaspy/DbDriverLoader.java, src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/TableOrderer.java, src/main/java/org/schemaspy/db/config/PropertiesFinder.java, src/main/java/org/schemaspy/db/config/PropertiesResolver.java, src/main/java/org/schemaspy/model/Catalog.java, src/main/java/org/schemaspy/model/Database.java, src/main/java/org/schemaspy/model/ForeignKeyConstraint.java, src/main/java/org/schemaspy/model/Schema.java, src/main/java/org/schemaspy/model/TableIndex.java, src/main/java/org/schemaspy/output/xml/dom/XmlTableFormatter.java, src/main/java/org/schemaspy/service/DatabaseService.java, src/main/java/org/schemaspy/util/DiagramUtil.java, src/main/java/org/schemaspy/util/Dot.java, src/main/java/org/schemaspy/util/GraphvizVersion.java, src/main/java/org/schemaspy/util/LineWriter.java, src/main/java/org/schemaspy/util/Markdown.java, src/main/java/org/schemaspy/view/DefaultSqlFormatter.java, src/main/java/org/schemaspy/view/HtmlMainIndexPage.java, src/main/java/org/schemaspy/view/HtmlTableDiagrammer.java, src/main/java/org/schemaspy/view/MustacheTableIndex.java, src/test/java/org/schemaspy/model/CatalogTest.java, src/test/java/org/schemaspy/model/SchemaTest.java, src/test/java/org/schemaspy/model/TableIndexTest.java
Most of these fix some sonar warnings
* Replace most printStackTrace() calls to use a logger - a few remain, they are grouped with a bunch of other System.out lines
* Remove some dead stores that were put in there a long time ago to "allow GC ASAP"
* Several classes had compareTo methods, but no equals / hashcode
* Switched a manual null check in a constructor to use `Objects.requireNonNull`
* There were a few uses of string concatenation inside of a loop, which isn't as efficient as allocating a StringBuilder (sonar  squid:S1643)
Fix the following IntelliJ warnings:
* for loop replaceable with foreach
* indexOf expression is replaceable with contains
* unnecessary boxing
* unnecessary unboxing
* Collections.sort could be replaced with List.sort
* Lambda can be replaced with method …
=> More cleanups

src/main/resources/org/schemaspy/types/hive-kerberos-driverwrapper-zookeeper.properties, src/main/resources/org/schemaspy/types/hive-kerberos-driverwrapper.properties, src/main/resources/org/schemaspy/types/hive.properties
Updated tableTypes for plain hive. Long list due to difference between distributions (cloudera, hdp)
* Added two for kerberized clusters using a driverwrapper, just kerberos and one with discoveryMode=zookeeper
=> Updates for hive

docs/source/configuration/databaseType.rst, src/main/java/org/schemaspy/service/TableService.java, src/test/java/org/schemaspy/service/TableServiceTest.java
Would be a fix for #215 but since It's a JDBC issue and it's reported to IBM.
This might not be wanted.
=> Exclude index column with ordinal 0

src/test/java/org/schemaspy/output/xml/dom/XmlTableFormatterTest.java
Booted up windows and withCheckConstraint test in XmlTableFormatterTest failed.
So fixed it by making expectation OS lineseparator dependent since I think the Transformer for DOM is.
=> Switched from \n to System.lineseparator()

docs/source/configuration/databaseType.rst, docs/source/configuration/schemaMeta.rst, src/main/java/org/schemaspy/db/config/PropertiesFinder.java, src/test/java/org/schemaspy/db/config/PropertiesFinderTest.java, src/test/resources/dbtypes/D0, src/test/resources/org/schemaspy/types/E0, src/test/resources/org/schemaspy/types/folder.properties
* Removed the possibility of reading files without extension.
We just add .properties if it's missing. Update docs.
* Fixed a wording issue in schemameta docs.
Fixes #229
=> Add validation that resource found in PropertiesFinder is a file

src/main/java/org/schemaspy/cli/CommandLineArgumentParser.java, src/main/java/org/schemaspy/cli/CommandLineArguments.java, src/main/java/org/schemaspy/cli/PropertyFileDefaultProvider.java, src/main/resources/commandlinearguments.properties, src/test/java/org/schemaspy/cli/CommandLineArgumentParserTest.java, src/test/java/org/schemaspy/cli/PropertyFileDefaultProviderTest.java
* Moved all validation outside of jCommander (one place)
CommandLineArgumentParser
* Enabled boolean handling of propertiesFile schemaspy.properties
`schemaspy.sso` and `schemaspy.debug`
* Added test for boolean handling
* Removed file-system dependency in CommandLineArgumentParserTest
* fixes #243
=> Made user argument conditionally required dependent on `-sso`

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/Main.java, src/main/java/org/schemaspy/db/config/PropertiesResolver.java, src/main/java/org/schemaspy/logging/LogLevelConditionalThrowableProxyConverter.java, src/main/java/org/schemaspy/model/InvalidConfigurationException.java, src/main/resources/application.properties
I read a comment that we might not want to print stacktraces in the faces of our users.
So just for fun I added a logback ThrowableConverter that only prints stacktrace if org.schemaspy logger is in level debug (which it is either by -debug or --debug)
Also altered some logging to make a good use-case.
So with no debug:
And with -debug:
The rational would be that we could add stacktraces to all logging and just have them skipped in normal flow and have them added in debug.
This would be to avoid
```
LOGGER.warn("Something went wrong");
LOGGER.debug("this is why", exception);
```
=> Only log stacktraces when -debug or --debug

src/main/resources/org/schemaspy/types/mysql.properties
If multiple databases have a table of the same name, the row count computed may be for the wrong database.
=> Fix mysql row count

src/main/java/org/schemaspy/model/xml/SchemaMeta.java, src/main/java/org/schemaspy/service/DatabaseService.java, src/test/java/org/schemaspy/integrationtesting/SchemaMetaIT.java
* Added fix for null comment so that it's ignored.
* Schema.comments can't be cleared only overwritten.
* Setting description is only possible from commandline.
Possible fix for #199
=> SchemaMeta comment updates db.getSchema().setComment(String)

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/validator/NameValidator.java, src/test/java/org/schemaspy/validator/NameValidatorIT.java, src/test/java/org/schemaspy/validator/NameValidatorTest.java
* The $ exclusion can now be overriden with `-I ""`
Solves #260 but retains current default.
So without the -I "" it will ignore tables with $ in table name. 
If they have used -I it will include them since it will overwrite default exclude which is .*\\$.* meaning any table name with $ in it.
=> Moved hardcoded exclusion of tables with $ to default exclusion.

docs/source/installation.rst
The old links were going to a 404 and a redirect page.
I repointed both to Graphviz's main Download page.
=> Update installation.rst with correct graphviz links

README.md
At least on linux (debian stretch) the command mvnw build did not work. mvn package created the jar I expected.
=> Fix building instructions

src/main/java/org/schemaspy/Config.java
The multi-schame analysis has been refactor and doesn't spawn a new java process as it did in 5.0
So the comment regarding passing on the commandline is invalid.
=> Removed invalid comment

src/main/java/org/schemaspy/service/DatabaseService.java, src/test/java/org/schemaspy/testcontainer/MysqlSchemaLeakageIT.java, src/test/resources/integrationTesting/mysql_schema_leakage/dbScripts/mysql_table_view_collision.sql
So, if SQL exists use it.
if SQL fails use DatabaseMetaData.
if SQL doesn't exist use DatabaseMetaData.
Problem isolated to mysql since they ignore SchemaPattern
(yes, they call it catalog)
Closes #222 with option 2
=> Never use both SQL and DatabaseMetaData in DatabaseService.getBasicTableMeta

src/main/resources/org/schemaspy/types/mssql05.properties, src/test/java/org/schemaspy/testcontainer/MSSQLServerIT.java, src/test/resources/integrationTesting/dbScripts/mssql.sql
In the default mssql05.properties file, the selectTableCommentsSql query does not include the schema when building the Object ID which causes joins to fail and comments to be skipped for tables. Adding the schema name resolves the issue.
=> Update mssql05.properties to include schema to prevent empty table comments

src/main/java/org/schemaspy/Main.java, src/main/java/org/schemaspy/SchemaSpyConfiguration.java, src/main/java/org/schemaspy/cli/CommandLineArgumentParser.java, src/main/java/org/schemaspy/cli/SchemaSpyRunner.java, src/test/java/org/schemaspy/MainTest.java, src/test/java/org/schemaspy/cli/CommandLineArgumentParserTest.java, src/test/java/org/schemaspy/cli/SchemaSpyRunnerTest.java, src/test/java/org/schemaspy/integrationtesting/StackTraceLoggingIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlHTMLIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlKeyWordTableIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlRoutinesIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlSpacesIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlSpacesNoDotsIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlXMLIT.java, src/test/java/org/schemaspy/testcontainer/InformixIndexIT.java, src/test/java/org/schemaspy/testcontainer/InformixIndexXMLIT.java, src/test/java/org/schemaspy/testcontainer/MSSQLServerIT.java, src/test/java/org/schemaspy/testcontainer/OracleIT.java, src/test/java/org/schemaspy/testing/ExitCodeRule.java
It closes the SpringContext and evals ExitCodeGenerator so that SpringContext can report an ExitCode. 
But since the returned ExitCode isn't used and we don't use any ExitCodeGenerators and we don't call System.exit with the returned value.
We should probably switch to SpringApplication.close and then use the ReturnCode provided to the exitApplication method in the System.exit call.
First commit with test, proves that there is a problem.
Second commit the fix in production code and tests should be come green.
=> Main.run doesn't call System.exit()

docs/source/configuration.rst, docs/source/configuration/commandline.rst
* Includes unimplemented/not used. If deprecated we should write so.
=> Added documentation of command-line arguments to read the docs.

src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/model/Database.java, src/main/java/org/schemaspy/service/DatabaseService.java, src/test/java/org/schemaspy/integrationtesting/H2KeywordIT.java, src/test/java/org/schemaspy/integrationtesting/H2SpacesIT.java, src/test/java/org/schemaspy/integrationtesting/H2ViewIT.java, src/test/java/org/schemaspy/integrationtesting/OracleSpacesIT.java, src/test/java/org/schemaspy/integrationtesting/SchemaMetaIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlKeyWordTableIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlRoutinesIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlSpacesIT.java, src/test/java/org/schemaspy/integrationtesting/mysql/MysqlSpacesNoDotsIT.java, src/test/java/org/schemaspy/service/DatabaseServiceIT.java, src/test/java/org/schemaspy/testcontainer/InformixIndexIT.java, src/test/java/org/schemaspy/testcontainer/MSSQLServerIT.java, src/test/java/org/schemaspy/testcontainer/OracleIT.java
* Since SchemaMeta augments the model it doesn't need to be part of it
* Also it's used in DatabaseService.gatheringSchemaDetails and
SchemaMeta is created lines above Database and right after creation
gatheringSchemaDetails is called.
* Removed connectTime
* Removed Exceptions from constructor
* Diamond clean up
=> Removing SchemaMeta from model

src/main/java/org/schemaspy/view/DotNode.java, src/main/java/org/schemaspy/view/HtmlFormatter.java, src/test/java/org/schemaspy/view/DotNodeTest.java
Moved methods only used by DotNode present in HtmlFormatter to DotNode
Updated tests.
=> Move methods only used in DotNode from HtmlFormatter

src/main/resources/org/schemaspy/types/sqlite-xerial.properties
In currently, sqlite JDBC driver that actively maintained is [xerial/sqlite-jdbc](https://github.com/xerial/sqlite-jdbc) and it get information easily. In usage of [bitbucket page](https://bitbucket.org/xerial/sqlite-jdbc), specify driver `org.sqlite.JDBC` instead of `SQLite.JDBCDriver`.
The driver `SQLite.JDBCDriver` might be that [sqlitejdbc](https://github.com/crawshaw/sqlitejdbc) has. But it currently not maintained, can't refer [official page](http://www.zentus.com/sqlitejdbc), and difficulty to get information.
And the driver uses `connectionSpec` to sqlite database file path. Prefixed `/` causes missing the file to specify root of filesystem. So remove it.
=> Fix sqlite.properties for xerial/sqlite-jdbc

src/main/java/org/schemaspy/service/TableService.java, src/test/java/org/schemaspy/service/TableServiceAddPrimaryKeyColumnTest.java, src/test/java/org/schemaspy/service/TableServiceIsIndexRowTest.java
This should replace #372 
Instead of having null pointer guards when used, null guard is placed when potentially null would be added to be able to extract as much information as possible in the case of null.
=> Primarykeys contains null

.travis.yml
So when tag is created either locally and pushed or in github.
Travis will build the artifact and upload it to releases as a draft.
This then den be bound to tag that was created.
In short you can create releases with binaries built by travis-ci
=> Added releases to deployment

src/main/resources/org/schemaspy/types/ora.properties
In the ora.properties file the selectRowCountSql is:
`selectRowCountSql=select table_rows row_count from information_schema.tables where table_name=:table`
Unfortunaly Oracle DB does not provide a Information Schema.
The ALL_TABLES metadata work fine for all Oracle DB.
=> fixed selectRowCountSql for Oracle DB

src/main/resources/org/schemaspy/types/ora.properties
this should solve https://github.com/schemaspy/schemaspy/issues/369
As guicampos mentioned - Oracle sometimes is a little special.
Oracle can group functions and procedures in packages. So there are no
"package parameters".
I do not use dba_xxx views and DBMS_METADATA.GET_DDL function - because
you need special rights on the database to use it
(eg SELECT_CATALOG_ROLE).
=> added selectRoutinesSql and selectRoutineParametersSql for Oracle DB

.travis.yml
There is a oraclejdk8 in the travis image. Don't try to update to latest, just causes pain.
Not with actual java, but with the update procedure.
=> Use included java version, don't update

src/test/java/org/schemaspy/output/html/mustache/diagrams/MustacheSummaryDiagramFactoryTest.java, src/test/java/org/schemaspy/util/ManifestUtilsIT.java
* MustacheSummaryDiagram FS supports posix for one test
* ManifestUtilsIT that its executed with surefire
(in path, normally by maven)
=> Added assumptions

src/main/java/org/schemaspy/cli/CommandLineArguments.java, src/main/java/org/schemaspy/cli/PropertyFileDefaultProvider.java, src/main/resources/commandlinearguments.properties, src/test/java/org/schemaspy/cli/CommandLineArgumentParserTest.java, src/test/java/org/schemaspy/cli/PropertyFileDefaultProviderTest.java
* nohtml is not an output attribute but an application/processing
End goal is to move progresslistener from the creation in SchemaAnalyzer to a bean, so it can be injected in multiple places and not passed as argument.
Later on this will help when switching from current progresslistener to an implementation with commandline progressbar.
=> Added nohtml to CommandLineArguments

src/main/java/org/schemaspy/Config.java, src/main/java/org/schemaspy/WiringConfiguration.java, src/main/java/org/schemaspy/service/DatabaseService.java, src/main/java/org/schemaspy/service/TableService.java, src/main/java/org/schemaspy/util/DurationFormatter.java, src/test/java/org/schemaspy/ConfigTest.java, src/test/java/org/schemaspy/service/DatabaseServiceTest.java, src/test/java/org/schemaspy/util/DurationFormatterTest.java
* Added clock to DatabaseService to test time based code.
* If Estimated time for completion of connectTables.views/tables is
longer than 30 minutes a logging will appear that the option
-noexportkeys exists and the implications of using it.
Solves issue #267
=> Added -noexportedkeys option to avoid lengthy calls to getExportedKeys()

pom.xml, src/main/java/org/schemaspy/logging/StackTraceOmitter.java
* fixes #506
* fixed possible defect or issue after dump related to stacktrace and
`-debug` advice
=> Bumped spring boot to version 2.1.2.RELEASE to avoid reflection warn

src/main/resources/org/schemaspy/types/db2i.properties
Hi,
I ran schemaspy-6.0.0 successfully on a DB2 for i V7R3m0 with the JDBC driver jtopen-9.8.
This is the configuration file.
=> Initial support for DB2 for i (former AS/400)

docs/source/configuration/commandline.rst
I am working with informix servers and tried to implement the '-noschema' argument but the Tag is not even used in Code so it always gives the same Error. In the Documentation I wanted to remove the sentence referring to '-noschema' argument. The same in 6.0.0 Documentation.
I hope we can improve the documentation alot more, because it would make my life much easier :)
=> commandline.rst updated - argument doesnt exist

src/main/resources/layout/anomalies.html, src/test/java/org/schemaspy/view/HtmlAnomaliesPageTest.java
I was wandering why i didnt get the column name of the single column table in the anomalie page, so i looked trough and there was a typo for which data to get from the Table List. so i changed it
=> Getting the column name of single column table

docs/source/started.rst
It was hard to find a working combination to connect with MS SQL Server, I added this in a comment line to make the "Get Started" easier on Microsoft SQL Server.
Another idea would be an extra page with several tested combinations of drivers.
=> additional comment to connect with MS SQL Server

docs/source/configuration/commandline.rst
additional one "/" is escaped because this prevent website simplifier to read the whole site
=> link added for Rails-based naming convention

src/main/java/org/schemaspy/util/Markdown.java, src/test/java/org/schemaspy/util/MarkdownTest.java
Do not convert `\n` to hard linebreaks
Only convert if it's preceded by two spaces
=> 623 Do not convert `\n` to hard linebreaks

docs/source/installation.rst
Here's a first crack at adding the JDBC driver requirement to the documentation and updating the requirements section.
I don't know if you officially support OpenJDK, but I added that as an option since it's working on my system.
Also, I tried to run `make make.bat` and `sphinx-build`, but they failed.  I saw a note in one of the other issues that Readthedocs probably does the compile step. I did include a few internal :ref links, but I can't really test them without something compiling the files.
Closes #747 
- Add a list of links to likely JDBC download locations for most of the supported engines
- Converted external links to text links
- Updated the Java section to include OpenJDK as an option
- Rework the viz.js or Graphviz requirement section
=> Update the Install Requirements, adding JDBC driver

docs/source/installation.rst
I also believe a build of the docs is required, since [the docs](https://schemaspy.readthedocs.io/en/latest/installation.html) do not have the latest version.
=> Add warning about Nashorn in Java 15

src/main/resources/org/schemaspy/types/pgsql.properties
As mentioned [here](https://wiki.postgresql.org/wiki/Slow_Counting), row count can be extremely slow for postgres with large tables.
This introduces custom SQL as recommended [here](https://wiki.postgresql.org/wiki/Count_estimate) for postgres instead of `count(*)` to get approximate row counts instead of hanging indefinitely for huge tables
=> Approximate row count for postgres

src/main/java/org/schemaspy/output/diagram/vizjs/VizJSDot.java, src/main/java/org/schemaspy/util/Writers.java
SVG should be UTF-8, but was written with system default encoding.
fixes #797 
fixes #669
=> fix(vizjs): write svg as utf-8

Dockerfile
Closes https://github.com/schemaspy/schemaspy/issues/849 by upgrading the Dockerfile to Java 17 (i.e. `openjdk:17-alpine3.14`).
=> Dockerfile: openjdk:17-alpine3.14

README.md, docs/source/advanced_usage.rst, docs/source/configuration/databaseType.rst, src/main/resources/org/schemaspy/types/h2-2.properties
Fixes #960.
It irritated me that I didn't find a list of supported database types in the documentation somewhere. So, how to document that for H2 2.x developers should set `-t h2-2`?
P.S. Note that this contains a separate commit that fixes some typos. Hence, I suggest to not squash this on merge.
=> Add support for H2 2.x

src/main/resources/org/schemaspy/types/h2-2.properties
* H2 1.x didn't have `start_value` it was introduced in 2.x
* 2.x is based of 1.x databaseType and as such it's inherited the workaround for `start_value`. It was overridden in 2.x since `current_value` has been replaced with `base_value` and 1.x during create set `current_value` to `START WITH - INCREMENT`, explains why it was `current_value + increment`
fixes #1012
=> fix(h2-2): use start_value

docs/source/_ext/schemaspy_database_types.py
* prepend path to database-types with `..` when building locally
=> fix(docs): path handling for rtd

src/main/resources/org/schemaspy/types/clickhouse.properties
Provide SchemaSpy doc generation support for ClickHouse database via [clickhouse-jdbc](https://github.com/ClickHouse/clickhouse-java/tree/main/clickhouse-jdbc)
=> Initial support for Clickhouse

src/main/java/org/schemaspy/cli/CommandLineArgumentParser.java, src/main/java/org/schemaspy/cli/CommandLineArguments.java, src/test/java/org/schemaspy/cli/CommandLineArgumentParserTest.java
Ability to handle JCommander unknown options, such as defined in dbType
=> chore(cli): store unknown options

docs/source/installation.rst, docs/source/started.rst
- Reworks and renames the "Download SchemaSpy" section in the [installation docs page](https://schemaspy.readthedocs.io/en/latest/installation.html)
- Adds a section under "Download SchemaSpy" [installation docs page](https://schemaspy.readthedocs.io/en/latest/installation.html) highlighting how to pull the Docker image and linking off to the Docker Hub page. This does not attempt to copy any of the more detailed Docker run information from Docker Hub.
- Renames "Requirements" to "Prerequisites"
- Adds a [_reST label_](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#cross-referencing-arbitrary-locations) in [Get Started page](https://schemaspy.readthedocs.io/en/latest/started.html) and a _:ref_ to "Get Started" in the Installation page.
As discussed at …
=> Docs: Tweak Installation page, Add Docker Download Section

src/main/java/org/schemaspy/cli/CommandLineArguments.java, src/main/java/org/schemaspy/cli/PropertyFileDefaultProvider.java, src/main/java/org/schemaspy/cli/SchemasListConverter.java, src/test/java/org/schemaspy/cli/CommandLineArgumentsTest.java
* Bug in jcommander loads same default for each option name/alias https://github.com/cbeust/jcommander/issues/457
=> chore(cli): set instead of list for schemas

.github/workflows/development.yml, .github/workflows/pr.yml, buildNumber.properties, pom.xml, src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/util/ManifestUtils.java, src/test/java/org/schemaspy/testing/ClassAvailableCondition.java, src/test/java/org/schemaspy/testing/EnableIfClassAvailable.java, src/test/java/org/schemaspy/util/ManifestUtilsIT.java, src/test/java/org/schemaspy/util/ManifestUtilsTest.java
* remove buildnumber-maven-plugin
* remove Implementation-Build
* add additional metadata to jar manifest
* add Implementation-Revision based on ${project.scm.tag} or -Dscm.revision
BREAKING CHANGE: Implementation-Build replaced by Implementation-Revision which is either commit sha or tag.
Old Manifest
```
Manifest-Version: 1.0
Created-By: Maven Jar Plugin 3.2.0
Build-Jdk-Spec: 11
Implementation-Build: 6.2.4.41 2023-07-21 11:24:46
Implementation-Version: 6.2.4
Main-Class: org.springframework.boot.loader.JarLauncher
Start-Class: org.schemaspy.Main
Spring-Boot-Version: 2.2.11.RELEASE
Spring-Boot-Classes: BOOT-INF/classes/
Spring-Boot-Lib: BOOT-INF/lib/
```
New Manifest
```
Manifest-Version: 1.0
Created-By: Maven Jar Plugin 3.2.0
Build-Jdk-Spec: 17
Build-Tool: Apache Maven 3.8.1 …
```
=> chore!: remove buildNumber.properties

docs/source/installation.rst
`download.html` 404s, `download/` does not.
=> Update download URL for PostgreSQL JDBC driver

docs/source/configuration/commandline.rst, pom.xml, src/main/java/org/schemaspy/SchemaAnalyzer.java, src/main/java/org/schemaspy/cli/CombinedDefaultProvider.java, src/main/java/org/schemaspy/cli/CommandLineArguments.java, src/main/java/org/schemaspy/util/markup/Asciidoc.java, src/main/java/org/schemaspy/util/markup/Markdown.java, src/main/java/org/schemaspy/util/markup/MarkupProcessor.java, src/main/java/org/schemaspy/view/HtmlMainIndexPage.java, src/main/java/org/schemaspy/view/HtmlRoutinePage.java, src/main/java/org/schemaspy/view/HtmlRoutinesPage.java, src/main/java/org/schemaspy/view/HtmlTablePage.java, src/main/java/org/schemaspy/view/MustacheCatalog.java, src/main/java/org/schemaspy/view/MustacheSchema.java, src/main/java/org/schemaspy/view/MustacheTableColumn.java, src/main/resources/commandlinearguments.properties, src/test/java/org/schemaspy/cli/CommandLineArgumentParserTest.java, src/test/java/org/schemaspy/integrationtesting/MarkupProcessorIT.java, src/test/java/org/schemaspy/util/MarkdownTest.java, src/test/java/org/schemaspy/util/markup/AsciidocTest.java, src/test/java/org/schemaspy/util/markup/MarkdownTest.java, src/test/java/org/schemaspy/util/markup/MarkupProcessorTest.java
We are currently using Asciidoc rather than Markdown to document our databases. This PR adds a new parameter (-asciidoc) that replaces the usages of the Markdown class with the Asciidoc class.
* Change the pages hashmap singleton with a singleton that encloses the complete MarkupProcessor
* Defaults to Markdown
* Adds a -asciidoc parameter
* Changes the way the reference links are handled to uniformize markdown processing with asciidoc
** Rather than adding `[link]: path` at the end of the Markdown string, it replaces the `[link]` directly.
* It also fixes #938
=> feature(Asciidoc): Allow the user to use Asciidoc as a markup language

docs/source/configuration/commandline.rst
There was a reference to a "-schemSpec" argument that should be "-schemaSpec".
=> Update commandline.rst - fix schemaSpec reference

docs/source/advanced_usage.rst
Just a typo in documentation.
s/postgresSQL/PostgreSQL/g
=> Fix typo in advanced_usage.rst
